name: FactoryRP
server:
  port: 9550

spring:
  profiles:
      active: dev

  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        generate_statistics: true  # 打开hibernate统计信息
        cache:
          use_second_level_cache: true # 打开二级缓存
          use_query_cache: true # 打开查询缓存
          ehcache:
            config: classpath:ehcache-jpa.xml
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory # 指定缓存provider
        hbm2ddl:
          auto: none
          #auto: update
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE # 配置shared-cache-mode

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: false

  #权限模块存储前缀
  auth:
    cache-prefix : factoryRP-Auth-user
    expiredTime : 216000 #设定过期时间为一小时
