name: FactoryRP
server:
  port: 9550


spring:
  active: dev
  datasource:
      url: jdbc:mysql://47.96.28.88:3306/factoryrp?useUnicode=true&characterEncoding=utf-8&useSSL=false
      ##url: jdbc:mysql://localhost:3306/factoryrp?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: developer
      password: hIRxhU2Qm5j1XlpFXGz8aiS6dKFGFiYFMQJMh2x8d1w
      ##username: root
      ##password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      druidMonitorUserName: admin
      druidMonitorPassword: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true  # 打开hibernate统计信息
        cache:
          use_second_level_cache: true # 打开二级缓存
          use_query_cache: true # 打开查询缓存
          ehcache:
            config: classpath:ehcache-jpa.xml
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory # 指定缓存provider
        hbm2ddl:
          auto: update
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE # 配置shared-cache-mode
  redis:
    #host: 10.108.60.20
    host: localhost
    port: 6379
    password:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  aop:
    auto: false

  #权限模块存储前缀
  auth:
    cache-prefix : factoryRP-Auth-user
    expiredTime : 216000 #设定过期时间为一小时

  #开始自动重启
  devtools:
      restart:
        enabled: true

